exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

title: Code for IATI
description: Tools and guidance contributed by community members, in support of IATI infrastructure, publishers and data users.

# Build settings
permalink: /blog/:year/:month/:day/:title/
pagine_path: "blog/page:num"
paginate: 10

gems: [jekyll-paginate]

collections:
  - projects

defaults:
  - scope:
      path: ""
    values:
      layout: default

navigation:
  - title: Projects
    slug: project
    url: /
  - title: Blog
    slug: blog
    url: /blog/

authors:
  codeforiati:
    name: Code for IATI
    display_name: Code for IATI
    email: hello@codeforiati.org
    web: https://codeforiati.org
    github: codeforiati
  mark:
    name: Mark Brough
    display_name: Mark
    email: hello@codeforiati.org
    web: https://codeforiati.org
    twitter: mark_brough
    github: markbrough
  andy:
    name: Andy Lulham
    display_name: Andy
    email: hello@codeforiati.org
    web: https://codeforiati.org
    twitter: andylolz
    github: andylolz