exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

description: Tools and guidance contributed by community members, in support of IATI infrastructure, publishers and data users.
title: Code for IATI

collections:
  - projects

defaults:
  - scope:
      path: ""
    values:
      layout: default

navigation:
  - title: Tools
    url: /
  - title: Blog
    url: /blog/
