exclude:
  - CNAME
  - README.md

description: Tools and guidance contributed by community members, in support of IATI infrastructure, publishers and data users.
title: Code for IATI

collections:
  - projects

defaults:
  - scope:
      path: ""
    values:
      layout: default
